"Configurations specific to GVIM
"Use the Solarized dark color scheme
set background=dark "set background=light
colorscheme solarized

"setup options for gvim GUI
set guioptions-=m "remove the menu bar
set guioptions-=T "remove the toolbar
set guioptions-=r "remove right hand scroll bar

if has("win32")
	set guifont=Consolas 18
endif
if has("unix")
	if system('uname')=~'Darwin'
		set guifont=Menlo\ Regular:h18
	else
		set guifont=Inconsolata\ Medium\ 18
	endif
endif

